name: "Build and Upload IPA"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: "Checkout repository..."
      uses: actions/checkout@v2
    - name: "Patch Xcode 15.3"
      uses: ./.github/actions/patch-package
    - name: "Build app and upload..."
      uses: ./.github/actions/ios-build-action
      with:
        project-path: "Diffusion.xcodeproj"
        p12-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: "iPhone Distribution: Carson Dunlap (4AVLVM82HR)"
        team-id: "4AVLVM82HR"
        certificate-password: ${{ secrets.CERTIFICATES_PASSWORD }}
        export-method: "app-store"
        configuration: "Release"
        scheme: "Diffusion"
        output-path: "DiffusionML.ipa"
        update-targets: "Diffusion"
        build-sdk: "iphoneos"
        entitlements-file-path: "Diffusion/Diffusion.entitlements"
        export-options: "Support/ExportOptions.plist"
        increment-build-number: "true"
        bundle-identifier: "com.carsonbdunlap.DiffusionML"
        app-store-connect-api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        app-store-connect-api-key-issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        app-store-connect-api-key-base64: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    - uses: Apple-Actions/upload-testflight-build@master
      with:
        app-path: "DiffusionML.ipa"
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
